version: '1.0'

services:
  web-api:
    build:
      context: ./EF
      dockerfile: Dockerfile
    ports:
      - 5000:8080
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  postgres:
    image: postgres:latest
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pg-data:
