services:
  promocode-factory-queue:
    image: rabbitmq:4.0.2-management
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: hole
    ports:
      - "15673:15672" # Management UI
      - "5673:5672" # Default RabbitMQ Port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  #Administration Db
  promocode-factory-administration-db:
    image: "postgres:latest"
    container_name: 'promocode-factory-administration-db'
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=docker

  #Administration Api
  promocode-factory-administration-api:
    build: src/Pcf.Administration/
    container_name: 'promocode-factory-administration-api'
    restart: always
    ports:
      - "8091:8080"
    environment:
      - "ConnectionStrings:PromocodeFactoryAdministrationDb=Host=promocode-factory-administration-db;Database=promocode_factory_administration_db;Username=postgres;Password=docker"
      - RabbitMQ__Host=amqp://rabbit:5672
      - RabbitMQ__Username=rabbit
      - RabbitMQ__Password=hole
    depends_on:
      - promocode-factory-administration-db
      - promocode-factory-queue

  #ReceivingFromPartner Db
  promocode-factory-receiving-from-partner-db:
    image: "postgres:latest"
    container_name: 'promocode-factory-receiving-from-partner-db'
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=docker

  #ReceivingFromPartner Api
  promocode-factory-receiving-from-partner-api:
    build: src/Pcf.ReceivingFromPartner/
    container_name: 'promocode-factory-receiving-from-partner-api'
    restart: always
    ports:
      - "8092:8080"
    environment:
      - "ConnectionStrings:PromocodeFactoryReceivingFromPartnerDb=Host=promocode-factory-receiving-from-partner-db;Database=promocode_factory_receiving_from_partner_db;Username=postgres;Password=docker"
      - "IntegrationSettings:GivingToCustomerApiUrl=http://promocode-factory-giving-to-customer-api"
      - "IntegrationSettings:AdministrationApiUrl=http://promocode-factory-administration-api"
      - RabbitMQ__Host=amqp://rabbit:5672
      - RabbitMQ__Username=rabbit
      - RabbitMQ__Password=hole
    depends_on:
      - promocode-factory-receiving-from-partner-db
      - promocode-factory-queue

  #GivingToCustomer Db
  promocode-factory-giving-to-customer-db:
    image: "postgres:latest"
    container_name: 'promocode-factory-giving-to-customer-db'
    restart: always
    ports:
      - 5436:5432
    environment:
      - POSTGRES_PASSWORD=docker

  #GivingToCustomer Api
  promocode-factory-giving-to-customer-api:
    build: src/Pcf.GivingToCustomer/
    container_name: 'promocode-factory-giving-to-customer-api'
    restart: always
    ports:
      - "8093:8080"
    environment:
      - "ConnectionStrings:PromocodeFactoryGivingToCustomerDb=Host=promocode-factory-giving-to-customer-db;Database=promocode_factory_giving_to_customer_db;Username=postgres;Password=docker"
      - RabbitMQ__Host=amqp://rabbit:5672
      - RabbitMQ__Username=rabbit
      - RabbitMQ__Password=hole
    depends_on:
      - promocode-factory-giving-to-customer-db
      - promocode-factory-queue

volumes:
  rabbitmq_data:


