name: CI

on:
  push:
    branches: ["homework-units"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./tests/YourTestProject.sln

      - name: Build
        run: dotnet build ./tests/YourTestProject.sln --no-restore

      - name: Run tests
        run: dotnet test ./tests/YourTestProject.sln --no-build --no-restore --verbosity normal
